version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "Hello World"
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - ./scripts/deploy-ghpages.sh build
